import {VolumeProfilerSettingsRowType} from '../../../services/volume-profiler/volume-profiler.service';

export interface TAIndicatorParameters {
    source?:string,
    source2?:string,
    periods?:number,
    period1?:number,
    period2?:number,
    period3?:number,
    period4?:number,
    standardDeviations?:number,
    maType?:string,
    shift?:number,
    minTick?:number,
    limitMove?:number,
    kPercentPeriods?:number,
    kPercentSmoothing?:number,
    kPercentDoubleSmoothing?:number,
    dPercentPeriods?:number,
    dPercentMaType?:string,
    barHistory?:number,
    r2Scale?:number,
    cycle1?:number,
    cycle2?:number,
    cycle3?:number,
    shortTerm?:number,
    longTerm?:number,
    pointsOrPercent?:number,
    rateOfChange?:number,
    shortCycle?:number,
    longCycle?:number,
    signalPeriods?:number,
    minAf?:number,
    maxAf?:number,
    levels?:number,
    conversionLinePeriods?: number,
    baseLinePeriods?: number,
    loggingSpan2Periods?: number,
    vpRowSize?:number,
    vpValueAreaVolumeRatio?:number,
    anchor?: string,
}
